# Generated by Django 6.0.4 on 2026-04-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkform',
            new_name='check_form',
        ),
    ]
